name: Build and test
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build_test:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
        node-version: ['20', '22']

    name: ${{ matrix.platform }} / Node.js v${{ matrix.node-version }}
    runs-on: ${{ matrix.platform }}
    steps:
      - run: git config --global core.autocrlf false # Preserve line endings
      - uses: actions/checkout@v4
      - name: Setup Node.js v${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm ci
      - name: Build packages
        run: npm run build
      - name: Lint packages
        run: npm run lint
      - name: Test packages
        run: npm test --if-present

  build_test_all:
    if: always()
    runs-on: ubuntu-latest
    needs: build_test
    steps:
      - name: Check build matrix status
        if: ${{ needs.build_test.result != 'success' }}
        run: exit 1
